Add stop script
onflow/kitty-items pull request #243
Opened 2022-04-21 17:01 UTC by louisguitton

Hi,
<img width="707" alt="image" src="https://user-images.githubusercontent.com/7823843/164513017-b0895e2e-4474-4307-b46c-ded06e3b17b4.png">

2022-04-22 22:54 UTC, 10thfloor approved these changes
Necessary!

2022-04-22 22:55 UTC, 10thfloor requested changes
I think you can just do `pm2 stop all`
Might be b

2022-04-22 22:55 UTC, 10thfloor commented on package.json
> +    "stop": "npx pm2 stop dev-wallet emulator api web"
```suggestion
    "stop": "npx pm2 stop all"
```

Might be better to stop all just to be safe?

2022-07-25 23:44 UTC, 10thfloor approved these changes
Too easy.

2022-07-25 23:49 UTC, merged

2022-07-25 23:50 UTC, MrDSGC commented
Thank you for improving the codebase @louisguitton! :)